name: Job Automation Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"

jobs:
  generate-jobs-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate jobs PDF
        run: python main.py

      - name: Upload jobs PDF
        uses: actions/upload-artifact@v4
        with:
          name: jobs-pdf
          path: jobs/*.pdf
          if-no-files-found: warn
